# 網站設定

# 匯入主題
theme: jekyll-theme-chirpy

# 網頁的語言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果與資料夾 `_data/locales`, 中的檔案名稱相同，版面語言也會改變，否則，版面語言將使用預設值 'en'。
lang: en

# 變更為您的時區 › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag 設定 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Chirpy # 主標題

tagline: A text-focused Jekyll theme # 將顯示為副標題

description: >- # 由 seo meta 和 atom feed 使用
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# 填入您網站的通訊協定與主機名稱。
# 例如 'https://username.github.io' ，注意它不是以 '/' 結尾。
url: "https://miguotw.github.io"

github:
  username: github_username # 變更為您的 GitHub 使用者名稱

twitter:
  username: twitter_username # 更改您的 Twitter 用戶名

social:
  # 改為您的全名。
  # 它會顯示為文章的預設作者，並在頁尾顯示為版權所有者
  name: your_full_name
  email: example@domain.com # 變更您的電子郵件地址
  links:
    # 第一個元素是版權所有者的連結
    - https://twitter.com/username # 變更到您的 Twitter 首頁
    - https://github.com/username # 變更到您的 GitHub 首頁
    # 請在下方取消註解，以加入更多社群連結
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 網站驗證設定
webmaster_verifications:
  google:  # 填入您的 Google 驗證碼
  bing: # 填入您的 Bing 驗證碼
  alexa: # 填入您的 Alexa 驗證碼
  yandex: # 填寫您的 Yandex 驗證碼
  baidu: # 填寫您的百度驗證碼
  facebook: # 填寫您的 Facebook 驗證碼

# ↑ --------------------------
# 以上是 jekyll-seo-tag 設定的結束

# 網頁分析設定
analytics:
  google:
    id: # 填入您的 Google Analytics ID
  goatcounter:
    id: # 填入您的 GoatCounter ID
  umami:
    id: # 填入您的 Umami ID
    domain: # 填入您的 Umami 網域
  matomo:
    id: # 填入您的 Matomo ID
    domain: # 填入您的 Matomo 網域
  cloudflare:
    id: # 填入您的 Cloudflare Web Analytics token
  fathom:
    id: # 填入您的 Fathom 網站 ID

# 頁面檢視設定
pageviews:
  provider: # 現在只支援 'goatcounter'

# 偏好色彩方案設定。
#
# 注意：保持為空，預設會沿用系統偏好的顏色。在側邊欄左下方會有一個切換鍵，可以在深色和淺色之間切換主題。
#
# 可用的選項：
#
# light - 使用淺色方案
# dark - 使用深色方案
#
theme_mode: # [light | dark]

# 媒體資源的 CDN 端點。
# 請注意，一旦指定，CDN 位址
# 將被加入所有以 '/' 開頭的媒體資源 (網站頭像、文章圖片、音訊和視訊檔案) 路徑中。
#
# 例如 'https://cdn.com'
cdn:

# 側邊欄上的頭像，支援本機或 CORS 資源
avatar:

# SEO `og:image` meta tag 中使用的全站社交預覽圖片的 URL。
# 它可以被前端自訂的 `page.image` 所覆寫。
social_preview_image: # 字串、本機或 CORS 資源

# boolean 類型，是文章中 TOC 的全局開關。
toc: true

comments:
  # 後置評論系統的全局開關。保持為空表示停用。
  provider: # [disqus | utterances | giscus]
  # 供應商的選項如下：
  disqus:
    shortname: # 填入 Disqus 的簡稱。 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # 聲音設定 › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus 選項 › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # 可選，預設為 'pathname'
    strict: # 可選，預設為 '0'
    input_position: # 可選，預設為 'bottom'
    lang: # 可選，預設的值為 `site.lang`
    reactions_enabled: # 可選，預設的值為 `1`

# 自託管靜態資產，可選 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: true # boolean，留空表示 false
    # 指定 Jekyll 環境，空表示兩者都有
    # 只有當 `assets.self_host.enabled` 為 'true' 時才有效
    env: # [development | production]

pwa:
  enabled: true # PWA 功能的選項 (可安裝)
  cache:
    enabled: true # PWA 離線快取的選項
    # 此處定義的路徑將會從 PWA 快取中排除。
    # 通常它的值是與目前網站共享相同網域名稱的另一個網站的 `baseurl`。
    # 與目前網站共享相同網域名稱。
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# 您網站的基本 URL
baseurl: "/NewIsland-wiki"

# ------------ 不建議修改下列選項 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
